# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Blyton
tagline:          'A Leveled Book Recommender'
description:      'Your book recommendation butler.'
url:              https://github.tamu.edu/ankurrc/cs670-Blyton
baseurl:          /

author:
  name:           'Team Blyton'
  url:            https://github.tamu.edu/ankurrc/cs670-Blyton/graphs/contributors

paginate:         5

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          1.0.0

github:
  repo:           https://github.tamu.edu/ankurrc/cs670-Blyton

